ALTER TABLE "EmailDelivery"
ADD COLUMN "subject" TEXT NOT NULL DEFAULT '',
ADD COLUMN "textBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastAttemptAt" TIMESTAMP(3);

ALTER TABLE "EmailDelivery"
ALTER COLUMN "subject" DROP DEFAULT,
ALTER COLUMN "textBody" DROP DEFAULT;
